Implement login route, change password route, and session tokens
cuappdev/old-eatery-blue-backend pull request #19
Opened 2022-03-23 06:26 UTC by markim21

EateryStore now stores an email, password, session token, and session token expiration date.
Implemented three routes:
- login: given an email and password, return a session token
- change password: given an email, current password, new password
- test (session token): given a session token, check if it's still valid

2022-03-26 19:44 UTC, connorreinhold requested changes
forgot to publish these comments

2022-03-26 19:44 UTC, connorreinhold commented on src/api/controllers/login_account.py
> +        self.new_password = new_password
generally updating password is done in a different way (so if u lose your old password your account isn't completely compromised) - can talk about this with email stuff!

2022-03-26 19:44 UTC, connorreinhold commented on src/api/controllers/login_account.py
> +            raise Exception("Invalid session token. Please log in again.")
wondering if we should have error codes to return so that when this specific error code is raised we force logout the frontend

2022-03-26 19:44 UTC, connorreinhold commented on src/api/controllers/login_account.py
> +            raise Exception("Invalid session token. Please log in again.")
this is just for the future ignore this for now

2022-03-26 19:44 UTC, connorreinhold approved these changes

2022-03-26 21:03 UTC, chalo2000 approved these changes
This looks good to me, nice job! I don't see a register route so I'm wondering how you went about testing this. Your PR isn't following AppDev's PR template, we need to make sure future PRs are following the template @connorreinhold. There needs to be a .github folder with the following file https://github.com/cuappdev/pear-django-backend/blob/main/.github/pull_request_template.md in order to get this to work. I'd also recommend when you're working on the register routes to include a salt to make the password more secure since they can be easily decrypted if the password database is compromised and passed through a rainbow table.

2022-03-26 21:03 UTC, chalo2000 commented on src/api/controllers/login_account.py
> +#from api.datatype.Eatery import get_password
delete comment if not being used

2022-03-26 21:03 UTC, chalo2000 commented on src/api/datatype/Eatery.py
> +    BEST_EATERY = 40
and this eatery is?

2022-03-31 15:14 UTC, alanna-zhou requested changes
nice first pr! you're doing an amazing job~

i do have some comments and they can be discussed after spring break as well

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +from rest_framework import status
imports should be alphabetized according to a precommit linter!

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    return EateryStore.objects.filter(id=id.value).first()
Why not `EateryStore.objects.get(id=id.value)` ?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    return EateryStore.objects.filter(email=email).first()
.get..?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    return EateryStore.objects.filter(session_token=session_token).first()
same

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    if bearer_token is None or not bearer_token:
is there a reason why you are also checking `not bearer_token`? not consistent with `auth_header` so im wondering

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        raise Exception("Malformed Request: missing bearer header")
do you actually want to raise an exception? or do you want to silently return a failure response?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        raise Exception("Malformed Request: missing bearer header")
raising exceptions are not always good, because the outerlevel has to do some catching

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    session_expiration = datetime.now() + timedelta(days=1)
this should be put in an `.envrc` or some constants file, people shouldn't know how long this takes to expire

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +
we don't need these white spaces, let's delete all of them

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        self.password = hasher.encode(password, "seasalt2")
why is `seasalt2` being revealed

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        user = EateryStore.objects.filter(id = self.id.value).first()
.get

also... why is it `id.value`....?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        if user.email == "":
to check empty strings, `if not user.email` should be good? you can double check in the python interpreter

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +            raise Exception("user already registered", status.HTTP_400_BAD_REQUEST)
raising exceptions... not the best...

Also, keep exception names consistent `"User already..."`

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +            raise Exception("user already registered", status.HTTP_400_BAD_REQUEST)
check `success` and `failure` responses in pear backend

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        pass
shouldn't this for now return `True`?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        return hasher.verify(self.password, password)
how can this work now..? since you're returning pass? has this been locally tested?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +
remove these white lines

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    def verify_password(self, password):
if this is a method that can only be seen by this controller, it needs to be `_verify_password`

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +        user = get_user_by_email(self.email)
_get_user_by_email

rename the method

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +
remove

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +
remove

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/controllers/login_account.py
> +    def verify_session_token(self, session_token, session_expiration):
_verify

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/datatype/Eatery.py
> +    BEST_EATERY = 40
these should all be in a constants file..?

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/datatype/Eatery.py
> +    BEST_EATERY = 40
and with comments explaining what the numbers mean

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/urls.py
> +    #path("password_reset_success", PasswordChangeSuccessView.as_view(), name="reset_success"),
let's not leave in comments

2022-03-31 15:14 UTC, alanna-zhou commented on src/api/views.py
> +            return JsonResponse(error_json(str(e)))
appdev isn't really a fan of dry catch excepts -- and in general this isn't a good style to follow

instead of raising exceptions it might be better to be passing along a boolean on whether or not a user successfully registered

2022-03-31 15:14 UTC, alanna-zhou commented on src/eatery_blue_backend/settings.py
> +    'accounts.hashers.PBKDF2WrappedSHA1PasswordHasher',
alphabetize

2023-01-30 21:48 UTC, closed without merging