Finish implementing all schedule functionality (modified and closed schedules)
cuappdev/old-eatery-blue-backend pull request #22
Opened 2022-04-17 22:01 UTC by Archit404Error

## Overview
This PR focuses on adding in functionality that enables eateries to modify their repeating schedules in the case of holidays or other exceptions. Also, it adds Alanna to CODEOWNERS so she also gets auto requested for PR review.

## Changes Made
- Created new model to deal with exceptions to repeated schedules, where each exception represents a modified or closed schedule
- Implemented a few new dfg nodes (ClosedSchedule, ModifiedSchedules, LeftMergeRepeatedEvents, and LeftMergeRegularEvents) to handle the manipulation of DB data into eatery menus for our API
- Refactored LeftMergeEvents to generalize it
- NOTE: I know the files I created for the nodes aren't named pythonically so let me know if I should re-name them before merging. Was planning on just refactoring all file names when we begin to restructure/decouple our codebase into MVC format but can also rename for this.

## Test Coverage
How I tested/how reviewers can test:
- Run bash reset_db.sh to handle restructuring the db file on your system to include new models
- Add new exceptions to api_scheduleexception table (need to do this manually since we don't have endpoints yet)
- Here's an example:
<img width="426" alt="Screen Shot 2022-04-17 at 5 56 15 PM" src="https://user-images.githubusercontent.com/22649594/163733471-bdce2c39-60c4-4578-8d61-7f068fdc4dbb.png">
- Ensure that the created exceptions go into effect -- if there is a repeating schedule it should be modified by the exception as intended
- Here is are examples of repeating schedules (also needs to be created in api_repeatingeventschedule table):
<img width="594" alt="Screen Shot 2022-04-17 at 5 57 19 PM" src="https://user-images.githubusercontent.com/22649594/163733528-e6b34fef-019b-42aa-bdf1-ac8ec45c390c.png">

## Related PRs or Issues (delete if not applicable)
PR to implement just repeating schedules: #20 

## Screenshots (delete if not applicable)

<details>

  <summary>The before v after of adding a closed schedule -- the parent event it points to, the one generated via repeating schedule 2, is removed</summary>

  
<img width="1423" alt="Screen Shot 2022-04-17 at 6 00 02 PM" src="https://user-images.githubusercontent.com/22649594/163733643-393e776a-dc4d-4b79-8449-6ea55d6e89f9.png">
<img width="1432" alt="Screen Shot 2022-04-17 at 6 00 08 PM" src="https://user-images.githubusercontent.com/22649594/163733647-d1916cb6-1e9c-43cf-9223-a2f80d14260a.png">

</details>

2022-04-17 23:09 UTC, alanna-zhou requested changes
nice job! some nits

also, this PR is too big, try to break things up next time!

2022-04-17 23:09 UTC, alanna-zhou commented on .github/CODEOWNERS
> +*	@Archit404Error @connorreinhold @chalo2000 @markim21 @alanna-zhou
lol

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/datatype/Event.py
> +        canonical_date: date,
what does canonical date mean

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/datatype/Event.py
> +        generated_by: Optional[int] = None,
what does this int mean

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/datatype/Event.py
> +            else None,
`event_json.get("generated_by")` does what you're doing

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/datatype/Event.py
> +def filter_range(
could you leave a docstring that explains what this is filtering? liek all events not within the start and end? or within the start and end?

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/dfg/nodes/macros/LeftMergeEvents.py
> +            right_val = [right[attr] for attr in attr_lst]
you're sure that all `attr` exist in `left` and `right`? if not you can do `left.get(attr)`

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/dfg/nodes/macros/LeftMergeEvents.py
>              elif left_val < right_val:
wait how can you compare a list like this

2022-04-17 23:09 UTC, alanna-zhou commented on src/api/dfg/nodes/schedule/CornellDiningEvents.py
> +            )
in order for lines 89-91 to not throw an error, `category_map[item["category"]] = []` must already be true. so you should just check if `category in category_map` then you append, otherwise your assumption is wrong for line 89

2022-04-18 00:34 UTC, Archit404Error commented on src/api/datatype/Event.py
> +        canonical_date: date,
The date that the event started. So if event goes from today at 11pm to tomorrow at 1am the canonical date is today. Will add documentation for this

2022-04-18 00:35 UTC, Archit404Error commented on src/api/datatype/Event.py
> +        generated_by: Optional[int] = None,
The id of the repeating schedule that generated this event (None if it wasn't generated by one)

2022-04-18 00:36 UTC, Archit404Error commented on src/api/datatype/Event.py
> +def filter_range(
I didn't write this code, it just got reformatted by my formatter lol, but I'll add a doctoring

2022-04-18 00:37 UTC, Archit404Error commented on src/api/dfg/nodes/macros/LeftMergeEvents.py
> +            right_val = [right[attr] for attr in attr_lst]
Yeah they should always exist based on how our code is currently structured but I'll change it to .get in case we change stuff in future

2022-04-18 00:38 UTC, Archit404Error commented on src/api/dfg/nodes/schedule/CornellDiningEvents.py
> +            )
I also didn't write this code but I'll add that check

2022-04-18 00:45 UTC, Archit404Error commented on src/api/dfg/nodes/macros/LeftMergeEvents.py
>              elif left_val < right_val:
Oops forgot to remove the elif. ==, <, > compare elements at corresponding indexes in lists in python so the if statement is fine and that elif wasn't getting executed anyway. Will update code to remove it.

2022-04-18 04:47 UTC, alanna-zhou approved these changes
nice!! very speedy i love it

2022-04-18 05:08 UTC, merged