[EateryBlue Refactor] [1/4] Restructured eatery-related files into MVC design pattern
cuappdev/old-eatery-blue-backend pull request #25
Opened 2022-04-23 23:02 UTC by Archit404Error

## Overview
This PR creates a new app called eatery which contains all models, views, and controllers that deal with eateries. I pulled these out of the central api app. Additionally, I pulled out all datatypes from api/ that pertained to eateries. This is one PR out of several that need to be made in order to further decouple the codebase and fully transition to MVC.

## Changes Made
The new eatery app has the following structure:
Models:
- EateryStore
Views:
- UpdateView
Controllers:
- UpdateEateryController
Datatypes:
- Eatery
- EateryAlert

## Test Coverage

Tested by running bash reset_db.sh to apply migrations. Then, because the newly created eatery_eaterystore table was empty and I had some other data linked to the old eatery table via foreign keys, I opened the sqlite file in my database browser and ran `INSERT INTO eatery_eaterystore SELECT * FROM api_eaterystore` before running `bash reset_db.sh` a second time to fully apply all remaining migrations (errored out the first time due to integrity error).

Then I went to /api and ensured everything worked as expected including the repeating schedules and schedule exceptions. I also ran a POST request to /update to make sure it also still worked correctly.

## Next Steps (delete if not applicable)
Factor out other views/models/controllers into distinct apps. Specifically:
- Reports
- Schedules
- Menus

2022-04-24 00:13 UTC, alanna-zhou requested changes
this PR looks like it has formatting stuff as well. could you make a separate pr just for formatting? it's difficult to review the stuff that is important

2022-04-24 00:13 UTC, alanna-zhou commented on src/api/admin.py
>  admin.site.register(models.SubItemStore)
you should be registering admin under `src/eatery/admin.py`

2022-04-24 01:35 UTC, chalo2000 approved these changes
Since I approved the unformatted version, I'll be approving this one as well.

2022-04-26 22:41 UTC, alanna-zhou approved these changes
nice!!

2022-04-27 21:06 UTC, markim21 approved these changes
Same comments as before! Looks good! :)

2022-05-08 23:35 UTC, merged