Create daily database population schedule
cuappdev/old-eatery-blue-backend pull request #40
Opened 2023-03-20 21:03 UTC by kidzegeye

## Overview

Made a schedule script that populates the model data every 24 hours

## Changes Made

- Create a `populate_models` command that populates the data of for each model in the same way that the `\cdn\populate\` endpoint does
- Create `schedule.py` which schedules the execution of `populate_models`
- Modify the docker-compose files to run `schedule.py` on startup

## Test Coverage

Tested locally by running `schedule.py` on its own and by running `docker-compose up` to see how it would behave in a container

## Next Steps (delete if not applicable)

Possibly delete the `\cdn\populate\` endpoint, as populating the tables takes too long, which causes the server to timeout

2023-03-20 21:40 UTC, mateow99 approved these changes
lgtm

2023-03-21 04:43 UTC, mateow99 approved these changes
lgtm but why did we need to switch from scheduler to cronjob?

2023-03-21 04:43 UTC, mateow99 commented on Dockerfile
> +RUN chmod 0744 manage.py
can you explain why these numbers? is there any reason to restrict privileges

2023-03-23 19:02 UTC, snajima requested changes
j some few nits here and there :)

2023-03-23 19:02 UTC, snajima commented on src/eatery/controllers/populate_eatery.py
> +        #else:
let's not leave in commented code

2023-03-23 19:02 UTC, snajima commented on docker-compose.yml
> +    command: sh -c "python manage.py migrate && printenv > /etc/environment && { cron -f & python manage.py runserver 0.0.0.0:8; }"
why are we running on port 8? 

also, consider changing `/etc/environment` to `/etc/profile.d/`: https://askubuntu.com/questions/866161/setting-path-variable-in-etc-environment-vs-profile

2023-03-23 19:25 UTC, kidzegeye commented on docker-compose.yml
> +    command: sh -c "python manage.py migrate && printenv > /etc/environment && { cron -f & python manage.py runserver 0.0.0.0:8; }"
Will the cronjob still be able to access the env vars if the environment variables are in /etc/profile.d/?

2023-03-23 19:39 UTC, kidzegeye commented on Dockerfile
> +RUN chmod 0744 manage.py
I found the crontab file in the old eatery repo, so I thought it would be better to use cron than a external library

2023-03-23 19:40 UTC, kidzegeye commented on Dockerfile
> +RUN chmod 0744 manage.py
> can you explain why these numbers? is there any reason to restrict privileges

Fixed

2023-03-25 16:42 UTC, snajima commented on docker-compose.yml
> +    command: sh -c "python manage.py migrate && printenv > /etc/environment && { cron -f & python manage.py runserver 0.0.0.0:8; }"
yeah, i don't think it's good to directly pipe into `/etc/environment`

instead pipe the output of `printenv | awk '{print "export " $0}'` into a `.sh` file in `/etc/profile.d/` (executed every shell initialization)

2023-03-25 16:43 UTC, snajima approved these changes
just change the `docker-compose.yml` issue addressed above and then we can get this merged :)

2023-03-29 21:31 UTC, merged