Implement Wait Times
cuappdev/old-eatery-blue-backend pull request #48
Opened 2023-04-23 16:58 UTC by mateow99

## Overview

Implement wait times using cornell swipe data

## Changes Made

- Get swipe data
- Calculate wait time using legacy formula
- return low, expected, high wait times

## Test Coverage

Tested using the django rest framework site

2023-04-23 17:01 UTC, kidzegeye approved these changes
LGTM

2023-04-24 19:59 UTC, snajima requested changes
a few stylistic changes but mainly more written documentation/comments to explain how wait times are calculated. we've always calculated wait times in not the best ways, so let's make sure everyone is on the same page and we don't go down the same rabbit hole

2023-04-24 19:59 UTC, snajima commented on docker-compose.server.yml
> +    image: cornellappdev/eatery-blue-dev:${IMAGE_TAG}
what is this change for?

2023-04-24 19:59 UTC, snajima commented on src/swipe/controllers/populate_wait_times.py
> +            return [18, 21, 24]
where do these numbers come from?

2023-04-24 19:59 UTC, snajima commented on src/swipe/controllers/populate_wait_times.py
> +
this is a HUGE function with no comments or spaces in between lines. let's add some comments and line separation for legibility + ease of understanding

2023-04-24 19:59 UTC, snajima commented on src/swipe/controllers/populate_wait_times.py
> +
ur also making the  `data`  variable in very similar ways three times in the same function. is there no way of condensing this?

2023-04-24 19:59 UTC, snajima commented on src/swipe/serializers.py
> +        int_to_day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
can we make `int_to_day` a global variable/constant? we use it several times throughout the codebase

2023-04-24 19:59 UTC, snajima commented on src/swipe/serializers.py
> +    wait_time_expected= serializers.IntegerField()
space after `wait_time_expected`

2023-04-24 20:04 UTC, mateow99 commented on src/swipe/controllers/populate_wait_times.py
> +            return [18, 21, 24]
legacy numbers we found

2023-04-24 20:04 UTC, mateow99 commented on docker-compose.server.yml
> +    image: cornellappdev/eatery-blue-dev:${IMAGE_TAG}
@kidzegeye

2023-04-24 20:18 UTC, mateow99 commented on src/swipe/controllers/populate_wait_times.py
> +
they are made differently each time so it wouldn't clean up too much to add a helper function

2023-04-24 20:30 UTC, kidzegeye commented on docker-compose.server.yml
> +    image: cornellappdev/eatery-blue-dev:${IMAGE_TAG}
The docker hub repository is called eatery-blue-dev. There doesn't exist a repo called eatery-blue-backend. But I think the reason it was set to eatery-blue-backend was that we would eventually get a prod server, so I guess we could change it now or later

2023-04-26 01:55 UTC, snajima requested changes
few things but once these r addressed i'll approve immediately

2023-04-26 01:55 UTC, snajima commented on src/swipe/models.py
> +        return int_to_day[i]
let's move this to a constants file rather than making it a function specifically for the wait time model

2023-04-26 01:55 UTC, snajima commented on src/swipe/controllers/populate_wait_times.py
> +                            print(json_eatery["name"])
can we make this initialization part a separate function call (this `process` function is really long)

2023-04-26 01:55 UTC, snajima commented on src/swipe/controllers/populate_wait_times.py
> +                    }
can we define `wait_time_low`, `wait_time_medium`, and `wait_time_high`; `trials` once; and define `wait_time` as `None` to reduce the number of lines here by half?
i.e. something like
```
try:
   wait_time = WaitTime.objects.get(eatery=eatery_id, day=day, hour=hour)
   trials = wait_time.trials + 1
   wait_time_low = (wait_time.wait_time_low*trials + low_time)/(trials+1)
   wait_time_expected = (wait_time.wait_time_expected*trials + expected_time)/(trials+1)
   wait_time_high = (wait_time.wait_time_high*trials + high_time)/(trials+1)
except ObjectDoesNotExist:
   wait_time = None
   trials = 1
   wait_time_low = low_time
   wait_time_expected = expected_time
   wait_time_high = high_time
serialized = WaitTimeSerializer(wait_time, data=data, partial=True)
if serialized.is_valid():
   serialized.save()
```

2023-04-26 21:37 UTC, snajima requested changes
much better, but old issues were put back into this from kidus's merge

2023-04-26 21:37 UTC, snajima commented on src/swipe/models.py
> +        return int_to_day[i]
this still needs addressing

2023-04-27 04:48 UTC, snajima approved these changes
lgtm!

2023-04-27 19:06 UTC, merged